### ISSUE TITLE
flag issue

### ISSUE THREAD

**Issue by rcon420** [KillStr3aK/scoreboardlevel#4]
I use for all of my icons flag 15 none of them work anyone can select them its same with different flags.
also if someone loses his access icon remains it should be removed soon as the person doesn't have a flag anymore.

**Comment by cazhjo** [comment]
@rcon420 I created a pull request #5 where I fixed the first part of this issue.
If you need a temporary solution, then change 15 to 32768 (since 1<<15 = 32768)

**Comment by rcon420** [comment]
> @rcon420 I created a pull request #5 where I fixed the first part of this issue.
> If you need a temporary solution, then change 15 to 32768 (since 1<<15 = 32768)

for now, I just use my VIP plugin to restrict access to the command. But it would be amazing if you added proper cookie support so icons get removed if the player no longer has access. Also, I think it would be better just to a specific letter of the flag :). Thank you for letting me know that you are still interested to update this plugin.  Edit oh you are not the author but thanks for pushing update anyway!

**Comment by cazhjo** [comment]
@rcon420 no worries, i actually had the same problem and by pure coincidence found your issue :).

**Comment by KillStr3aK** [comment]
> > @rcon420 I created a pull request #5 where I fixed the first part of this issue.
> > If you need a temporary solution, then change 15 to 32768 (since 1<<15 = 32768)
> 
> for now, I just use my VIP plugin to restrict access to the command. But it would be amazing if you added proper cookie support so icons get removed if the player no longer has access. Also, I think it would be better just to a specific letter of the flag :). Thank you for letting me know that you are still interested to update this plugin. Edit oh you are not the author but thanks for pushing update anyway!

Merged @cazhjo pr, however these plugins will be reworked soon

**Comment by rcon420** [comment]
> > > @rcon420 I created a pull request #5 where I fixed the first part of this issue.
> > > If you need a temporary solution, then change 15 to 32768 (since 1<<15 = 32768)
> > 
> > 
> > for now, I just use my VIP plugin to restrict access to the command. But it would be amazing if you added proper cookie support so icons get removed if the player no longer has access. Also, I think it would be better just to a specific letter of the flag :). Thank you for letting me know that you are still interested to update this plugin. Edit oh you are not the author but thanks for pushing update anyway!
> 
> Merged @cazhjo pr, however these plugins will be reworked soon

damn waiting still on the updates :)
